import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.concurrent.ThreadLocalRandom;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    //Method to roll dices and generate array of rolled values
    public static int roll(int n) {
        int counter = 0;
        int[] values = new int[n];
        while (counter < n) {
            for (int i = 0; i < values.length; i++) {
                int num = ThreadLocalRandom.current().nextInt(1, 7);
                values[i] = num;
                counter++;
            }
            System.out.println(Arrays.toString(values));
        }
        return values.length;
    }

//New Method to Check for duplicates

    public static boolean containsDuplicates(ArrayList<Integer> nums) {
        for (int i = 0; i < nums.size(); i++) {
            if (nums.contains(i) == nums.contains(i + 1)) {
                return true;
            }
        }
        return false;
    }

    public static int averageCalculator (int[] numArray) {
        int arraySum = 0;
        for (int i = 0; i < numArray.length; i++) {
            arraySum += numArray[i];
        }
        int average = arraySum / numArray.length;
        return average;
    }
}





