/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
//testing for rolls
    @Test public void testRoll() {
        Library classUnderTest = new Library();
        int expected = 3;
        int rolls = Library.roll(3);
        assertEquals(expected, rolls);
    }
    //testing duplicates
    @Test public void testContainsDuplicates() {
        Library classUnderTest = new Library();
        int[] num = new int[4];
        num[0]=1;
        num[1]=2;
        num[2]=2;
        num[3]=4;

        assertTrue("containDuplicates method should return 'true' if it contains duplicates", Library.containsDuplicates(num));

        int[] num1 = new int[4];
        num1[0]=1;
        num1[1]=2;
        num1[2]=3;
        num1[3]=4;
        assertFalse("containDuplicates method should return 'false' if it contains no duplicates", Library.containsDuplicates(num1));
    }
    //Testing for average calculator
    @Test public void testAverageCalculator() {
        Library classUnderTest = new Library();
        int[] nums = new int[4];
        nums[0] = 1;
        nums[1] = 2;
        nums[2] = 3;
        nums[3] = 4;
        int expected = 2;

        assertEquals(expected,Library.averageCalculator(nums));
    }

    //Testing for lowest average

    @Test public void LowestCalculator() {
        Library classUnderTest = new Library();
        int[][] nums = new int[3][2];
        nums[0][0] = 1;
        nums[0][1] = 2;
        nums[1][0] = 2;
        nums[1][1] = 2;
        nums[2][0] = 3;
        nums[2][1] = 3;

        int[] expected = {1,2};

        assertArrayEquals(expected,Library.lowestAverage(nums));
    }
}
