/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
//testing for rolls
    @Test public void testRoll() {
        Library classUnderTest = new Library();
        int expected = 3;
        int rolls = Library.roll(3);
        assertEquals(expected, rolls);
    }
    //testing duplicates
    @Test public void testContainsDuplicates() {
        Library classUnderTest = new Library();
        ArrayList<Integer> guess = new ArrayList<>();
        guess.add(1);
        guess.add(2);
        guess.add(3);
        guess.add(4);
        boolean ans = Library.containsDuplicates(guess);
        assertTrue("containDuplicates method should return 'true'", ans);
    }
    //Testing for average calculator
    @Test public void testAverageCalculator() {
        Library classUnderTest = new Library();
        int[] nums = new int[4];
        nums[0] = 1;
        nums[1] = 2;
        nums[2] = 3;
        nums[3] = 4;
        int expected = 2;
        int ans = Library.averageCalculator(nums);
        assertEquals(expected,ans);
    }

    //
}
