import java.text.DecimalFormat;
import java.util.ArrayList;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Restaurant { //extends Review
    public String name;
    public float numStars;
    public String price; //i.e. number of dollar signs).


    public Restaurant(String name, int numStars, String price) {
        this.name = name;
        this.numStars = numStars;
        this.price = price;

    }
    @Override
    public String toString() {
        DecimalFormat df = new DecimalFormat("##.0");
        return this.name + df.format(this.numStars) + this.price;
    }

    public void addReview(Review review) {
        ArrayList<Integer> numStarsArr = new ArrayList<>();
        numStarsArr.add(review.numStars);
        if(this.numStars<0){
            float sum =this.numStars +review.numStars;
            this.numStars = sum/numStarsArr.size();
        }else{
            float sum =this.numStars +review.numStars;
            this.numStars = sum/(numStarsArr.size()+1);
        }

    }
}
