/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testToStingMethod() {
        Restaurant classUnderTest = new Restaurant("RedRobin", 2,"$");
        String message = "RedRobin2$";
        assertEquals(message, classUnderTest.toString());
    }

    @Test public void testToStingMethodExtend() {
        Restaurant classUnderTest = new Restaurant("RedRobin", 2,"$");
        String message = "RedRobin2$";
        assertEquals(message, classUnderTest.toString());
    }

    @Test public void testToConfirmExtend() {
        Restaurant classUnderTest = new Restaurant("Burger King", 4, "$");

        Review burgerKing = new Review("good", "zahra", 5);
        //should add 4 and 9
        String message = "Burger King4.5$";
        classUnderTest.addReview(burgerKing);


        assertEquals(message, classUnderTest.toString());

    }

}
