import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.Buffer;
import java.nio.file.*;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        //read from the file
        Path path = FileSystems.getDefault().getPath("resources/error-free.js");
        //call the function
        linterForJs(path);
    }
    public static void linterForJs(Path file){

        try (BufferedReader reader = Files.newBufferedReader(file)){
            String currentLine = "";
            int lineNum = 0;
            while (currentLine != null){
                //LOGIC
                if(!currentLine.isEmpty() && !currentLine.contains("{") && !currentLine.contains("}") && !currentLine.contains("if") && !currentLine.contains("else") && !currentLine.contains(";") && !currentLine.contains("//")){
                    System.out.println("Line "+lineNum+": Missing semicolon");
                }
                currentLine = reader.readLine();
                lineNum++;
            }
        }catch (IOException x){
            System.err.format("IOException: %s%n", x);
        }
    }
}
